apiVersion: apps/v1
kind: Deployment
metadata:
  name: serverapp-ui
spec:
  selector:
    matchLabels:
      app: serverapp-ui
  replicas: 2
  template:
    metadata:
      labels:
        app: serverapp-ui
    spec:
      containers:
      - image: rakneo/serverapp-ui:v1.0.0
        imagePullPolicy: Always
        name: serverapp-ui
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: serverapp-ui
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
  selector:
    app: serverapp-ui