apiVersion: apps/v1
kind: Deployment
metadata:
  name: serverapp-service
spec:
  selector:
    matchLabels:
      app: serverapp-service
  replicas: 2
  template:
    metadata:
      labels:
        app: serverapp-service
    spec:
      containers:
      - image: rakneo/goalsapp-svc:3
        imagePullPolicy: Always
        name: serverapp-service
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_URL
          valueFrom:
            secretKeyRef:
              name: serverapp-secrets
              key: mongo_url
---
apiVersion: v1
kind: Service
metadata:
  name: serverapp-service
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
  selector:
    app: serverapp-service

